services:
  ocr_service:
    #    build: .
    image: ghcr.io/kivvi3412/au_video_summarizer:latest
    container_name: AuVideoSummarizer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    restart: always
    volumes:
      - au_video_summarizer:/app
    ports:
      - "7860:7860"
    environment:
      - API_KEY=sk-key
      - BASE_URL=https://api.openai.com/v1
      - MODEL=deepseek-r1-250120

volumes:
  au_video_summarizer: